export enum PokeGame {
  lets_go_pikachu = 1,
  lets_go_eevee = 2,
  sword = 3,
  shield = 4,
  brilliant_diamond = 5,
  shining_pearl = 6,
  legends_arceus = 7,
  scarlet = 8,
  violet = 9,
  go = 10,
  isle_of_armor_sword = 11,
  isle_of_armor_shield = 12,
  crown_tundra_sword = 13,
  crown_tundra_shield = 14,
  home = 15,
}
