export * from './pokedex-data/pokedex-data.service';
export * from './pokedex-options/pokedex-options.service';
export * from './pokedex-search/pokedex-search.service';
export * from './pokedex-selection/pokedex-selection.service';
export * from './pokedex-storage/pokedex-storage.service';
export * from './pokedex-ui-service/pokedex-ui-service.service';
export * from './pokedex-statistics/pokedex-statistics.service';
export * from './pokedex/pokedex.service';
export * from './pokedex-dialog/pokedex-dialog.service';
