export enum CountFormsPolicy {
  COUNT_ALL = 'COUNT_ALL',
  NO_COUNT_INTERCHANDABLE = 'NO_COUNT_INTERCHANDABLE',
  NO_COUNT_VISUAL_ONLY = 'NO_COUNT_VISUAL_ONLY',
  NO_COUNT_VISUAL_ONLY_AND_INTERCHANDABLE = 'NO_COUNT_VISUAL_ONLY_AND_INTERCHANDABLE',
  NO_COUNT = 'NO_COUNT',
}
